### ISSUE TITLE
Pushed More Markup

### ISSUE THREAD

**Issue by dorothealint** [dorothealint/William_Combe_Works#14]
@alnopa9 I pushed markup for the First Tour of Dr Syntax, which is different from the one you have.  There are several and the first one isn't transcribed online anywhere that I found so I started.  It's not the complete work but it is enough to put something up.  Combe's work that everybody recognizes should at least be started on the page!

I also pushed a file that contains the div for the copy left designation which should go at the bottom of the index page.  I don't want to screw up the spacing you have on those web pages at this time in the semester!

And I pushed my full assignment with the attempt at an xslt timeline that I did.

**Comment by alnopa9** [comment]
Okay! I'm trying to sort out the collapsible Modern Spectator sidebar but then I'll add the copy left to the bottom of index.html as well as add the First Tour of Dr. Syntax. 
Also, I was just looking up more info about Combe and I found this page that lists a majority of his works:
https://en.wikisource.org/wiki/Combe,_William_(DNB00)

**Comment by alnopa9** [comment]
I just updated the server. The copy left is now on the bottom if index.html and First Tour of Doctor Syntax is on the site with internal links to each canto. I'm working on the toggle and switches for Modern Spectator now.

**Comment by dorothealint** [comment]
@alnopa9 Are all the Modern Spectator letter signatures marked with a "signature" attribute on the persName?
That would be ok to do the xslt to pull a list of them from.
