### ISSUE TITLE
Group meeting times?

### ISSUE THREAD

**Issue by dorothealint** [dorothealint/William_Combe_Works#3]
I am available after class every Monday Wednesday and Friday.  I usually hang out in the center for digital text until about 2.
I can also do Tuesday or Thursday meetings if need be

**Comment by alnopa9** [comment]
* **Monday** 4:30 - whenever
* **Tuesday** 4 - whenever
* **Wednesday** 4:30 - 7
* **Thursday** 4 - whenever
* **Friday** 2 - whenever
I need to know beforehand when you would want to have a meeting because I work part  time on Tuesdays, Thursdays, and Fridays.

**Comment by ghbondar** [comment]
Thanks for the invite!

**Comment by ghbondar** [comment]
@emb184 Hi, Emily! Here in the Combe project repo is the place for most project-specific posts. The easiest way to find the repo is to simply go to the main github.com page. Once you are logged-in, all of the repos to which you have been invited should be listed on the left.

**Comment by emb184** [comment]
I can meet after class for half an hour Monday or Wednesday, 2 on Monday, 1-2 on Wednesday and Friday, or after 4 on those days. Tuesdays and Thursdays I can meet after 5 or between 11:30 and 1. Sorry this took so long! Life is crazy.

**Comment by ghbondar** [comment]
@dorothealint @alnopa9 @emb184 What day and time each week is your group meeting?
