### ISSUE TITLE
Image for website

### ISSUE THREAD

**Issue by dorothealint** [dorothealint/William_Combe_Works#4]
Would this be legal to use on the website?  It seems to be public domain.
Team members, do you like it?  It is from his major work, the one people have actually heard of.
https://commons.wikimedia.org/wiki/File:SYNTAX(1813)_-_27_-_The_Doctor%27s_Dream.jpg

@ghbondar  @ebeshero @alnopa9 @emb184

**Comment by dorothealint** [comment]
And this one if it is really a portrait of him.
https://commons.wikimedia.org/wiki/File:William_Combe,_drawn_by_Georg_Dance,_1793._National_Portrait_Gallery.jpg

**Comment by ghbondar** [comment]
@dorothealint Yes, I think these are both fine to use, so long as you include the the public domain tagging that they provide.
